services:
  frontend:
    image: holyholi/movies
    ports: ["3000:3000"]
    environment:
      REACT_APP_API_URL: http://backend:8000/api/v1
    depends_on:
      - backend

  backend:
    image: webbylabhub/movies
    ports: ["8000:8000"]